### PR TITLE
Add section 4 descriptions

### LINKED ISSUE #13: Describe Registry Path and Value section
The new section on Registry Path and Value needs some introductory text to explain that its intent is to describe where in the document the profile may be identified, and where the profile definition document can be found, etc.

### PR DESCRIPTION
**Pull request by nigelmegitt**
Describe section 4 and the two tables.

Fixes #13.

### CODE REVIEW

**Comment by frans-ebu** [comment]
@nigelmegitt I see two '#' at the end of the URLs pointing to the requester contact of etx1, ext2, etd1
I'd suggest the '#' character should be removed.

https://tech.ebu.ch/ebu-tt# -> https://tech.ebu.ch/ebu-tt

**Comment by nigelmegitt** [comment]
@frans-ebu that's independent of this pull request and issue - sorry to be a pain but please could you raise it as a separate issue?

**Comment by frans-ebu** [comment]
understood, done: https://github.com/w3c/tt-profile-registry/issues/29

**Comment by nigelmegitt** [comment]
Thank you!

**Pull request merged**
