### PR TITLE
Clarify codecs parameter syntax requirements (#63).

### LINKED ISSUE #63: The codecs parameter and media type registration.
A reminder that any changes to the media type information in section 2 requires IANA and IETF expert review through the normal process between W3C and IANA. This should be done before publication.

The codecs parameter was created to be used in ISO BMFF and DASH MPD. Thus, it needs to conform to RFC 6381 syntax.  That is, the entire codecs parameter string must conform to RFC 6381 (not just the profile code).  The RFC 6381 citation should be moved to the codecs parameter text.

If we want to constrain the charset of the profile code, then we can point to 4CC in ISO/IEC 14496-12. Note that a recent update to that constrained 4CC to a subset of ASCII (0x20-0x7E).

### PR DESCRIPTION
**Pull request by skynavga**
Closes #63.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/tt-profile-registry/pull/69.html" title="Last updated on Mar 14, 2019, 2:17 AM UTC (0e4938a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/tt-profile-registry/69/a6edd37...0e4938a.html" title="Last updated on Mar 14, 2019, 2:17 AM UTC (0e4938a)">Diff</a>

### CODE REVIEW

**Review by nigelmegitt — APPROVED** [review]
Looks good to me.

**Review by cconcolato — DISMISSED** [review]
I'm not sure the note as is really useful. It's true that the codecs parameter of TTML follows a specific pattern, either a 4CC or a set of +/|-combined 4CCs, but the purpose of this section should not be about how the codecs in TTML is a specific subset of the general RFC6381 one. The note in this section could rather say: "the restriction on the + and | signs is required to enable the use of these signs in the codecs parameter, as defined in the MIME type registration". We could add a note in the MIME type saying: "Note that in this MIME type registration the first element (as defined in RFC6381) of the codecs parameter may contain a combination of 4CC and the + and | signs".

**Comment by skynavga** [comment]
@cconcolato regarding https://github.com/w3c/tt-profile-registry/pull/69#pullrequestreview-214615001 the purpose of this PR is to implement the WG's resolution stated in https://github.com/w3c/tt-profile-registry/issues/63#issuecomment-470599428, no more and no less; what you propose goes beyond the resolution, so please file a new issue if you think it necessary (I do not)

**Comment by skynavga** [comment]
@cconcolato since you have filed #71 to deal with your comment above, can you complete the review here and approve, thanks!

**Comment by skynavga** [comment]
No further comments received, so am merging given 14 days have passed.

**Pull request merged**
