### PR TITLE
Add support for IMSC 1.1 Text and Image Profile

### LINKED ISSUE #40: Add IMSC 1.1 profiles

### PR DESCRIPTION
**Pull request by palemieux**
Closes #40

### CODE REVIEW

**Comment by nigelmegitt** [comment]
It's good to have this ready to go, but I think it may be too soon to merge now, especially since we have not completed discussions about the idea to merge image and text profiles, which seems to meet some use cases that cannot be met any other way.

**Comment by palemieux** [comment]
Yes, more time is necessary for folks to review the PR.

I do not however think it makes sense to hold-off a merge for requirements that may never come and for which there has been no concrete interest from key IMSC 1.1 stakeholders. Furthermore, the addition of a mixed image-text profile would not necessarily remove any of the existing profiles.

**Review by cconcolato — APPROVED** [review]

**Comment by palemieux** [comment]
@nigelmegitt Your re-review would be appreciated.

**Comment by nigelmegitt** [comment]
It looks fine to me, but shouldn't we wait until IMSC 1.1 has proceeded to Rec?

**Comment by palemieux** [comment]
> It looks fine to me, but shouldn't we wait until IMSC 1.1 has proceeded to Rec?

I tend to agree.

**Comment by cconcolato** [comment]
There is a chicken and egg problem here. We cannot add example to IMSC1.1 because the code point is not registered and we cannot register the code point because IMSC1.1 is not final... Note that MPEG's CMAF amendment uses it too.

**Comment by mikedo** [comment]
As we move into TTML2-based profiles, remember that TTML1 and the registry is (to date) only about processor profiles not content profiles: "Note Well that, in the context of this registry, when we use the term profile, we mean processor profile. We explicitly do not mean content profile. That is, nothing about the use of the profile parameter described here is intended to be used to identify or make claims about whether a TTML resource conforms with a TTML Content Profile..."

This is at odds with CMAF content profiles of course.

**Comment by nigelmegitt** [comment]
> As we move into TTML2-based profiles, remember that TTML1 and the registry is (to date) only about processor profiles not content profiles

@mikedo that's a good point. Are you suggesting we restructure the document to specify content profiles as well as processor profiles? I think it would be rather less useful and create more dependency complexity if we were to create a new TTML2 profiles document in addition to this TTML1-based profiles document.

**Comment by nigelmegitt** [comment]
Re https://github.com/w3c/tt-profile-registry/pull/36#issuecomment-406643777 I raised #38 @mikedo .

**Review by nigelmegitt — APPROVED** [review]

**Pull request merged**
