### PR TITLE
fixing typos

### PR DESCRIPTION
**Pull request by dret**

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Thanks @dret - are you able to join the TTWG? This would mean that I can then add you to the group for pull requests and remove the "PR has contribution issues..." error. I don't see any specific IPR issues with this PR now, but it makes the process a bit easier if you're able to join, and that would pave the way for you to submit a PR for the issue #17 too if you wish to do that.

**Comment by dret** [comment]
On 2016-05-16 05:58, Nigel Megitt wrote:

> Thanks @dret https://github.com/dret - are you able to join the TTWG?
> This would mean that I can then add you to the group for pull requests
> and remove the "PR has contribution issues..." error. I don't see any
> specific IPR issues with this PR now, but it makes the process a bit
> easier if you're able to join, and that would pave the way for you to
> submit a PR for the issue #17
> https://github.com/w3c/tt-profile-registry/issues/17 too if you wish
> to do that.

i am trying to change my corporate affiliation so that i am recognized 
as a member, and then can probably join the WG. but from what i've seen 
so far, other groups accepted editorial changes like this without a 
problem because the IPR of typos may not be such a big deal ;-)

**Comment by nigelmegitt** [comment]
@dret you're github profile shows your affiliation as CA Technologies, which is listed as a member of W3C. Is it the github profile that's wrong? If it's correct, hopefully you know your AC rep for CA Technologies and can request group membership that way.

As I said, in this case I don't believe there's a contribution issue here, but I'm not sure what will happen if I merge it when it doesn't pass all checks - just being lazy on my part for the time being, but since you've mentioned that you'd like to contribute a more substantive change it's worth sorting it out now if possible.

**Comment by dret** [comment]
On 2016-05-17 03:42, Nigel Megitt wrote:

> @dret https://github.com/dret you're github profile shows your
> affiliation as CA Technologies, which is listed as a member of W3C. Is
> it the github profile that's wrong? If it's correct, hopefully you know
> your AC rep for CA Technologies and can request group membership that way.

i attenpted to update my w3c account yesterday (i only joined CA 
yesterday) but the change did not show up in my w3c account profile, and 
so far i have not received an answer for my support request.

> As I said, in this case I don't believe there's a contribution issue
> here, but I'm not sure what will happen if I merge it when it doesn't
> pass all checks - just being lazy on my part for the time being, but
> since you've mentioned that you'd like to contribute a more substantive
> change it's worth sorting it out now if possible.

sure, and thanks for letting me know. i will try to update my account 
again today, and maybe the w3c support team can make the change soon.

**Comment by dontcallmedom** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by nigelmegitt** [comment]
Thanks @dontcallmedom please could you let me know how you did that?

**Comment by dontcallmedom** [comment]
I did this with the brand [new feature in ash-nazg](https://github.com/w3c/ash-nazg/issues/17) (and in fact, to test it in a live context:).

When a PR is marked as not acceptable, if you follow the link to [the repository manager](https://labs.w3.org/hatchery/ash-nazg/), you'll now have an option to mark the PR as non-substantive, which clears the IPR flag.

**Comment by nigelmegitt** [comment]
Awesome - that's exactly what we need for cases like this. Thanks @dontcallmedom !

**Comment by dret** [comment]
thanks!

**Comment by nigelmegitt** [comment]
@mikedo ping - are you happy to merge this?

**Comment by dret** [comment]
thanks for merging!

**Pull request merged**
